### PR TITLE
Use imagepalettetotruecolor to convert paletted images to true color

### LINKED ISSUE #498: GD driver does not handle well transparency in PNG images
Using Imagick, the transparency of png images is handled correctly, but as I have memory usage problem (which are not present when using GD), I have to use GD. But the resulting images (which are thumbnails of another image) has a black background instead of transparent background, in png format.

Raw png :

Imagick Result :
51-thumb

GD Result :

Code used :

``` php
#!/usr/bin/env php
<?php
use Imagine\Image\Box;
use Imagine\Image\ImageInterface;

use Imagine\Gd\Imagine as GdDriver;
use Imagine\Imagick\Imagine as ImagickDriver;

require __DIR__ . '/vendor/autoload.php';

const THUMB_WIDTH = 640;
const THUMB_HEIGHT = 480;
const RESOLUTION = 200;
const RAW = __DIR__ . '/raw.png';

$imagine = [
    'gd' => new GdDriver,
    'imagick' => new ImagickDriver
];

$options = [
    'format' => 'png',
    'png_compression_level' => 0,

    'resolution-units' => ImageInterface::RESOLUTION_PIXELSPERINCH,
    'resolution-x' => RESOLUTION,
    'resolution-y' => RESOLUTION
];

foreach ($imagine as $name => $driver) {
    $slide = $driver->open(RAW);

    $path = sprintf('%s/thumb-%s.png', dirname(RAW), $name);

    $thumbed = $slide->thumbnail(new Box(THUMB_WIDTH, THUMB_HEIGHT));
    $thumbed->save($path, $options); // do not alter quality
}

return 0;
```

### PR DESCRIPTION
**Pull request by mlocati**
Since PHP 5.5, we can use the [imagepalettetotruecolor](http://php.net/manual/en/function.imagepalettetotruecolor.php) to convert a a palette based image to true color.

This fixes #498 (at least for PHP 5.5 and later), and avoid creating a second image resource.

### CODE REVIEW

**Comment by mlocati** [comment]
PS: to better view what's changed, see https://github.com/avalanche123/Imagine/pull/585/files?w=1

**Comment by MrKarlDilkington** [comment]
I tested this pull request and it correctly applies transparency to PNG8 images.

Before and after test images can be seen here:
https://github.com/concrete5/concrete5/issues/3999#issuecomment-365892134

**Comment by mlocati** [comment]
Thank you for confirming that this works, @MrKarlDilkington !

**Comment by robfrawley** [comment]
@mlocati Would it not be appropriate to implement unit test(s) that ensure transparency continues to work in this context as expected moving forward?

**Comment by mlocati** [comment]
I [added the tests](https://github.com/avalanche123/Imagine/pull/585/commits/f9c8c30d4a87ea8b5eb93431dbb34f7588019dd7), and managed to [fix loading indexed PNG files with alpha even for old (pre-5.5) PHP versions](https://github.com/avalanche123/Imagine/pull/585/commits/ec963df5f7e34f915773f80e971505c86d56c188).

What's still not working is the GMagick driver, which I'm not able to test.

**Comment by mlocati** [comment]
I found (and fixed) a few other bugs:
- Gmagick *does* support grayscale  images (see https://github.com/avalanche123/Imagine/pull/585/commits/dd1e039f075bf7efa116df0ea0eb619a63092662)
- Gmagick *does* support transparency (see https://github.com/avalanche123/Imagine/pull/585/commits/0ce00717f5cd72ad5b0e0131d3b4a15cff62d77f)
- Gmagic's `getColorAt` was buggy (see https://github.com/avalanche123/Imagine/pull/585/commits/b24c02b374f7ddee3e156892a394c1b2a1457f57)

All the above fixes are covered by the [`testImageAlphaLoaded`](https://github.com/avalanche123/Imagine/pull/585/files#diff-3b389fee1c088fed044f6cada2c10a0aR750) test included in this PR (which is now much more than what its title suggests).

**Comment by MrKarlDilkington** [comment]
This pull request includes many useful fixes, I look forward to its merge.

**Comment by typoman76** [comment]
As a graphic desinger I use often transparent images. Merging this fix would help a lot.

**Comment by a3020** [comment]
Great work from @mlocati (as always!). I've also noticed the transparency bug. I'm glad that a fix may be available in an upcoming release. :+1:

**Comment by ramonleenders** [comment]
Not only graphic designers use PNG files with transparency, so a fix like this is very much appreciated.

**Comment by JohntheFish** [comment]
@robfrawley, what is the release cycle? can this be merged for the next release?

**Pull request merged**
