### PR TITLE
Add THUMBNAIL_UPSCALE setting

### PR DESCRIPTION
**Pull request by vlakoff**
This setting allows upscaling the source image if needed,
so that the result matches the requested size instead of being smaller.

### CODE REVIEW

**Comment by stof** [comment]
@vlakoff note that I'm **not** the maintainer of this library. It is not me who need to review this to give it a merge.

**Comment by vlakoff** [comment]
Indeed, but by bringing false alarms you may slow down the approval of the PR. We are at six months already. And yep I got a bit angry, because meanwhile I have to complexify *a lot* my code to have this feature...

**Comment by stof** [comment]
@vlakoff my own reviews would allow to give it a better chance to be ready when @romainneutron reviews it.
Note that he is in vacation currently, so he won't review it in the coming days

**Comment by tetronomis** [comment]
+1

**Comment by vlakoff** [comment]
Please, don't [bump](https://en.wikipedia.org/wiki/Internet_forum#Bumping) this issue. That's only nine months. We are so close to a whole year. And I want to see if I die of old age before the patch makes it :)

**Comment by mlocati** [comment]
I rebased this PR and created #645

**Pull request closed without merging**
