### PR TITLE
Added trimImage option for Imagick

### PR DESCRIPTION
**Pull request by antonioperic**

### CODE REVIEW

**Comment by romainneutron** [comment]
Hello and thanks for your work.

However, we can not integrate driver-only feature in imagine. If you want to create such feature, I recommend you to create your own service and apply them using Imagick\Image::getImagick method

**Comment by igormukhingmailcom** [comment]
By the way there are driver-independent implementation of trim function.
See 4-th message at https://github.com/liip/LiipImagineBundle/issues/586
It has conditional for using `Imagick`'s built-in `trimImage` function for more performance.

**Comment by antonioperic** [comment]
@igormukhingmailcom did you add this at the end?
I resolved my case with listener it works, but it will be nice to have trim filter inside

**Comment by igormukhingmailcom** [comment]
@antonioperic I used that code (maybe with some small modifications) only on my project and not performed any PR yet.

**Comment by antonioperic** [comment]
@igormukhingmailcom thnx for sharing it

**Comment by igormukhingmailcom** [comment]
@antonioperic I thinking around how to test code right way. Because same `fuzz` may give different result for native `Imagick`'s and self-writed output. 

I think that should be some source image with linear gradient to test with. And both functions must remove same part of image during `trim`.

**Comment by AlmogBaku** [comment]
Any update about adding @igormukhingmailcom PR? (well kinda PR)

**Comment by antonioperic** [comment]
@AlmogBaku I don't think this option will be merged see comment at the begging. But from code you can see how to use it.

**Comment by igormukhingmailcom** [comment]
@AlmogBaku Hi. That code example can't be added, because it designed to use as extension for LiipImagineBundle at AppBundle. So you can copy-paste it to your AppBundle to use.

**Pull request closed without merging**
