### PR TITLE
Fixing tests

### PR DESCRIPTION
**Pull request by burzum**

### CODE REVIEW

**Comment by robfrawley** [comment]
Re: https://github.com/avalanche123/Imagine/issues/521#issuecomment-277558880

Just pushed a commit to #528 with the changes need to use `phpunit` version `5.3`. Prior, there was no `script` section, which means Travis will use the "global" (system installed) version of `phpunit`. Installing it using "global" `composer`, as you were trying, does so in the "user" scope (which would still need a special runtime configuration to be called). I removed that, as the `composer.json` already specifies the version requirement, thus it will be installed in the "project" scope. At this point, it can be called by the addition I made to `composer.json`:

```yml
script:
  - ./bin/phpunit -vvv
```

Still failing, but it is using the version of `phpunit` desired.

**Comment by robfrawley** [comment]
Also, I removed the `composer self-update` command, as Travis already does this during its bootstrapping process. See [line 138](https://travis-ci.org/avalanche123/Imagine/jobs/198689121#L138) from a recent build.

**Comment by robfrawley** [comment]
@burzum The `hirak/prestissimo` package need to be added globally for it to have any affect; moreover some configuration needs to be in place. I recently added it to the Travis build for `liip/imagine-bundle` and you can reference my pull request there for inspiration: liip/LiipImagineBundle#864.

**Comment by romainneutron** [comment]
Superseeded by #530

**Pull request closed without merging**
