### PR TITLE
Fix WEBP support in GD driver

### PR DESCRIPTION
**Pull request by ausi**
Fixes several issues with handling WEBP images with the GD driver:

- `imagecreatefromstring()` doesn’t support WEBP in PHP versions lower than 7.3.0 ac7609d5d977474874b8e4873210fd64774645b3
- `webp_quality` option was ignored 75d75a1daf0ad8a1267e2780969d7e6d9eccd3d8
- Supported formats didn’t check if `webp` is actually available f85731be229e769d817975e40003d54bddb542df

This pull request is an alternative to #711, it uses less code and doesn’t require a temp directory.

@mlocati is it OK to have all those fixes in a single pull request or should I create one PR for every fix?

### CODE REVIEW

**Comment by ausi** [comment]
The failed build on Travis CI (PHP 5.5 imagick) doesn’t seem to be related to my changes.

**Comment by mlocati** [comment]
Rewritten as #719 (I like to give credits to every contributor):

**Comment by ausi** [comment]
Thank you @mlocati!

I noticed that my changes from `AbstractImagineTest` and `AbstractImageTest` didn’t get copied over.  
If that wasn’t on purpose, I’m happy to create another pull request with the tests if you want me to.

**Comment by mlocati** [comment]
@ausi My fault: I should have added them

**Pull request closed without merging**
