### PR TITLE
Support AVIF and HEIC in Imagick driver

### PR DESCRIPTION
**Pull request by ausi**
This adds support for AVIF and HEIC in the Imagick driver as suggested in #742 and #755.

~~This is still a work in progress. Saving files already works fine, but reading images files currently fails because imagemagick (incorrectly?) reports `Imagick::COLORSPACE_YCBCR` as the colorspace even though it is RGB. Just ignoring this doesn’t seem to work because the color profile doesn’t get interpreted correctly then (tested with an iPhone HEIC image).~~

### CODE REVIEW

**Comment by ausi** [comment]
I was able to fix the colorspace issue by the suggested fix from @jleckie in #756. Now the color profile gets applied correctly and the colors stay the same with my test files.

**Comment by ausi** [comment]
The failing tests do not seem to be related to this pull request.

**Comment by laxity7** [comment]
So what about this MR? Obviously, the solution is working, the problem is outside of this MR. 

Can you accept it? Doesn't work with heic without it

**Comment by mlocati** [comment]
@ausi Do you have a working environment for imagick + HEIC?
I'm trying to fix the tests: they now use Docker images (built by https://github.com/php-imagine/docker-builder/blob/main/.github/workflows/create-images.yml and https://github.com/php-imagine/docker-builder/blob/main/docker/installer.sh)
In the imagick tests we have errors like [this one](https://github.com/php-imagine/Imagine/runs/3807085250?check_suite_focus=true#step:7:39):

```
Imagine\Test\Imagick\ImageTest::testSaveCompressionQuality with data set #5 ('heic', array(0), array(100))
Imagine\Exception\RuntimeException: Save operation failed

src/Imagick/Image.php:343
tests/tests/Image/AbstractImageTest.php:1031
tests/tests/Imagick/ImageTest.php:179

Caused by
ImagickException: no encode delegate for this image format `HEIC' @ error/constitute.c/WriteImage/1272

src/Imagick/Image.php:341
tests/tests/Image/AbstractImageTest.php:1031
tests/tests/Imagick/ImageTest.php:179
```

**Comment by ausi** [comment]
Do we need to add the `--with-heic` and other flags to https://github.com/php-imagine/docker-builder/blob/f0e428b7ec295aef48ae674711cb4cbf81ad22e3/docker/installer.sh#L235 ?

**Comment by mlocati** [comment]
Nope: it's detected automatically: see https://github.com/php-imagine/docker-builder/runs/3806674769?check_suite_focus=true#step:11:1144

I'll try to see of installing some additional libraries fixes the issue (the script you linked above is very helpful)

**Comment by mlocati** [comment]
I understood what's missing: libheif uses libde265 to read heic files, and libx265 to write them: I only installed libde265

**Comment by mlocati** [comment]
See https://github.com/php-imagine/docker-builder/pull/2/commits/24e54b8b28f6b184a25fba1541b128a3991ca4be

**Comment by laxity7** [comment]
When will the release be?
The master does not yet have these changes, but it is very necessary.

And thanks for being active

**Pull request merged**
