### PR TITLE
Transparent background when rotate an image (gd)

### PR DESCRIPTION
**Pull request by prokopov-nikolai**

### CODE REVIEW

**Comment by mlocati** [comment]
Why don't you use the `$background` parameter of the `rotate` method to specify a transparent background?

**Comment by prokopov-nikolai** [comment]
Can you write an example?

**Comment by mlocati** [comment]
> Can you write an example?

```php
$gd = new Imagine\Gd\Imagine();
$palette = new Imagine\Image\Palette\RGB();
$transparent = $palette->color('#000', 0);
$image = $gd->open($inputFilename);
$image->rotate(45, $transparent);
$image->save($outputFilename);
```

**Comment by prokopov-nikolai** [comment]
Thank you. I'll try this method.

**Comment by mlocati** [comment]
> Thank you. I'll try this method.

Please close this pull request if this method works for you.

**Pull request closed without merging**
