### PR TITLE
applyMask() fix in Gd/Image

### PR DESCRIPTION
**Pull request by ninze**
Created applyMask() fix for #460

### CODE REVIEW

**Comment by ausi** [comment]
I’m not sure if this fix is correct. I think `applyMask()` is meant to be used with a grayscale image.

Did you try to use `->applyMask($mask->mask());` as described in https://github.com/avalanche123/Imagine/issues/460#issuecomment-425042314 ?

**Comment by systemist** [comment]
@ausi yes I did without success. The fix makes imagine work consistently with both GD and Imagick drivers. We are using this fix in production since April without any issues.

**Comment by mlocati** [comment]
Is it possible to have a test case that covers what this PR is fixing?

**Comment by ninze** [comment]
It probably is, will look into it.

**Comment by ninze** [comment]
Done. I don't have gmagick installed, but GD and Imagick produce identical results after the fix.

**Comment by jakubjo** [comment]
> @ausi yes I did without success. The fix makes imagine work consistently with both GD and Imagick drivers. We are using this fix in production since April without any issues.

Maybe it's about time someone merges this?

**Comment by ninze** [comment]
After more than 2 years since the pull request was created, I also think someone should either merge or close this.

**Review by ausi — APPROVED** [review]
Tested this pull request locally and all worked correctly.

In the old code `->dissolve(…)` could have never ended up with a negative value and therefore could never have masked anything.

**Comment by mlocati** [comment]
Thanks for reviewing this PR, @ausi !

**Comment by chekalsky** [comment]
@mlocati thank you! is it possible to release new version of Imagine?

**Comment by mlocati** [comment]
@chekalsky I'd publish a new version after tests have been fixed (I'd move them to GotHub Actions)

**Pull request merged**
