### PR TITLE
support resize of animated gifs with imagick

### PR DESCRIPTION
**Pull request by scuben**
support of resizing images with multiple layers with imagick.

feedback very welcome!

### CODE REVIEW

**Comment by armatronic** [comment]
@romainneutron this should build properly once it's rebased onto develop, since the build issues have been resolved since this PR was opened.

**Comment by talbotseb** [comment]
Any idea what still needs to be done for this PR to be merged ?

**Comment by armatronic** [comment]
@talbotseb as far as I know only the CI checks were failing, I've been using this in production for a while now.

**Comment by trsteel88** [comment]
@romainneutron this appears to work. Any update on when this will be merged.

Fyi, the casing is incorrect for 2 methods in the code. It should be "coalesceImages" and "deconstructImages"

**Comment by trsteel88** [comment]
@scuben, you might want to fix that method casing btw.

**Comment by dupuchba** [comment]
It would be great to get this implemented, can someone re-launch the build ?

**Comment by burzum** [comment]
@dupuchba I would like to but I can't. :( @avalanche123 can you?

**Comment by mlocati** [comment]
Included in #481 (that was already merged).

**Pull request closed without merging**
