### PR TITLE
Try to reproduce the 'no encode delegate' in the unit tests

### PR DESCRIPTION
**Pull request by leofeyer**
See #732 and #733.

### CODE REVIEW

**Comment by leofeyer** [comment]
I think I have managed to reproduce the issue on Travis:



https://travis-ci.org/avalanche123/Imagine/jobs/660247300#L1681-L1685

Next I am going to commit the fix and see if the builds pass.

**Comment by mlocati** [comment]
> I think I have managed to reproduce the issue on Travis:

Well, also the `WEBP` test case fails, not only the `webp` one...

**Comment by leofeyer** [comment]
Correct. The fix did not fix the issue. 😞

**Comment by leofeyer** [comment]
@ausi told me that he will have a look at this again tonight.

**Pull request closed without merging**
