### PR TITLE
Enable past with alpha transparency

### PR DESCRIPTION
**Pull request by drmovi**
set alpha transparency for overlay image

### CODE REVIEW

**Comment by stof** [comment]
having a different signature than the interface does not make sense. It defeats the point of being an abstraction library

**Comment by drmovi** [comment]
This is suggestion to add transparency feature to past function

**Comment by stof** [comment]
@drmovi but then, it must be added in the interface and implemented for all libraries.

And I'm not sure changing the existing method is a good idea. It might have unwanted side effects

**Comment by drmovi** [comment]
3 libraries , i think that is not a big deal

**Comment by burzum** [comment]
@drmovi any plans to finish this PR? I agree with @stof, it doesn't make sens to merge this without his proposed changes.

**Comment by mlocati** [comment]
Implemented in #639

**Pull request closed without merging**
